[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "web-scraper"
version = "0.0.0"
readme = "README.md"

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
namespaces = false