
# Redis Configuration
redis:
  db: 0
  socket_timeout: 5
  decode_responses: true
  max_connections: 10

  # Queue Names
  queues:
    high: "articles:queue:high"
    medium: "articles:queue:medium"
    low: "articles:queue:low"

# MongoDB Configuration
mongodb:

# Scraper Configuration
scraper:
  request:
    timeout: 10
    max_retries: 3
    retry_delay: 2

  selenium:
    headless: true
    implicit_wait: 10
    timeout: 30
    no_sandbox: true

    # Fallback to Selenium if standard requests fail
    enabled_fallback: true
    required_elements: ["title"]

consumer:
  poll_interval: 2 # sec to wait when queue are empty
  max_articles: null
  batch_size: 1

publisher:
  input_file: "data/data.json"
  clear_queue_on_start: false
  batch_size: 10

# Dashboard Configuration
dashboard:
  enable_cors: true
  cors_origins: "*"